
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  fm3:
    build:
      context: .
    image: fm3:0.0.3
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://johndoe:randompassword@postgres:5432/fm3?schema=public
    depends_on:
      - postgres

volumes:
  postgres:
